<lolspeak> 	    ::=	<noun_phrase> <verb> <noun_phrase>
<noun_phrase>	::=	<article> <adjective> <noun>
<adjective>     ::= fat | hungry | happy | mean
<verb>	 	    ::=	lovez  |  hatez  | ates
<noun>	 	    ::=	dawg  |  kat  |  rat
<article>	    ::=	a  | teh
